- id: homeassistant_update_notification
  alias: ⚙️HomeAssistant Update notification
  trigger:
  - platform: state
    entity_id:
    - update.home_assistant_core_update
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_10pro
    data:
      message: Home Assistant {{states.update.home_assistant_core_update.attributes.latest_version}}
        is available.
      title: "\U0001F195 Update Available!"
      data:
        notification_icon: mdi:package-up
        subject: "You are running {{states.update.home_assistant_core_update.attributes.installed_version
          }}, the latest\n    version is {{ states.update.home_assistant_core_update.attributes.latest_version
          }}."
        clickAction: /config/dashboard
        icon_url: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/google/313/partying-face_1f973.png
  mode: single
- id: spotify_playback
  alias: "\U0001F3B5Spotify Selected Device Force playback"
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.speakers_spotify
  condition: []
  action:
  - service: script.spotify_start
  mode: single
- id: movies_on_plex
  alias: "\U0001F3ACMovies"
  trigger:
  - platform: event
    event_type: tag_scanned
  condition:
  - condition: template
    value_template: '{{ trigger.event.data.tag_id in tags }}'
  action:
  - variables:
      media_content_id: '{{ tags[trigger.event.data.tag_id].media_content_id }}'
      media_content_type: '{{ tags[trigger.event.data.tag_id].media_content_type }}'
      announce_name: '{{ tags[trigger.event.data.tag_id].announce_name }}'
  - choose:
    - conditions:
      - condition: not
        conditions:
        - condition: state
          entity_id: media_player.google_tv
          state: Plex
          attribute: source
      sequence:
      - service: media_player.select_source
        target:
          entity_id: media_player.google_tv
        data:
          source: Plex
      - wait_template: '{{ not is_state(''media_player.plex_plex_for_android_tv_google_tv'',
          ''unavailable'') }}'
        timeout: 00:00:10
      - service: media_player.play_media
        target:
          entity_id: media_player.plex_plex_for_android_tv_google_tv
        data:
          media_content_id: '{{ media_content_id }}'
          media_content_type: '{{ media_content_type }}'
    - conditions:
      - condition: state
        entity_id: media_player.google_tv
        state: Plex
        attribute: source
      sequence:
      - service: androidtv.adb_command
        data:
          entity_id: media_player.google_tv
          command: BACK
      - service: media_player.media_stop
        target:
          entity_id: media_player.plex_plex_for_android_tv_google_tv
        data: {}
      - service: media_player.select_source
        target:
          entity_id: media_player.google_tv
        data:
          source: Plex
      - service: media_player.play_media
        target:
          entity_id: media_player.plex_plex_for_android_tv_google_tv
        data:
          media_content_id: '{{ media_content_id }}'
          media_content_type: '{{ media_content_type }}'
    default: []
  mode: parallel
  max_exceeded: silent
  variables:
    media_players:
      device_id: media_player.plex_plex_for_android_tv_google_tv
    tags:
      D7-02-2C-7B:
        media_content_id: '{ "library_name": "Movies", "title": "sontham"}'
        media_content_type: movie
        announce_name: Playing Sonthham
      87-1A-2D-7B:
        media_content_id: '{ "library_name": "Movies", "title": "tamasha"}'
        media_content_type: movie
        announce_name: Playing Tamasha
      37-A5-38-7B:
        media_content_id: '{"library_name": "Movies", "title": "Raanjhanaa"}'
        media_content_type: movie
        announce_name: Playing Raanjhanaa
      87-D2-29-7B:
        media_content_id: '{"library_name": "Movies", "title": "rudraveena"}'
        media_content_type: movie
        announce_name: Playing Rudraveena
      17-EA-2F-7B:
        media_content_id: '{"library_name": "Movies", "title": "vedam"}'
        media_content_type: movie
        announce_name: PLaying Vedam
      37-FA-2A-7B:
        media_content_id: '{ "library_name": "Movies", "title": "96"}'
        media_content_type: movie
        announce_name: Playing 96
      F7-57-2B-7B:
        media_content_id: '{ "playlist_name": "Mayabazar", "shuffle": "1" }'
        media_content_type: playlist
        announce_name: Playing Mayabazaar
      07-5F-2B-7B:
        media_content_id: '{ "playlist_name": "Friends", "shuffle": "1" }'
        media_content_type: playlist
        announce_name: Playing a Friends Episode
      E7-2B-3A-7B:
        media_content_id: '{ "playlist_name": "Batman Trilogy", "shuffle": "1" }'
        media_content_type: playlist
        announce_name: Playing a movie from the Batman Trilogy
      07-CE-2C-7B:
        media_content_id: '{ "playlist_name": "MCU", "shuffle": "1" }'
        media_content_type: playlist
        announce_name: Playing A movie from MCU
      77-FD-37-7B:
        media_content_id: '{ "playlist_name": "DC", "shuffle": "1" }'
        media_content_type: playlist
        announce_name: Playing A movie from DC EU
      17-58-39-7B:
        media_content_id: '{ "playlist_name": "K Vishwanath Movies", "shuffle": "1"}'
        media_content_type: playlist
        announce_name: Playing a movie by K Vishwanath
      47-26-28-7B:
        media_content_id: '{ "playlist_name": "Doctor Who", "shuffle": "1"}'
        media_content_type: playlist
        announce_name: Playing a Doctor Who Episode
      47-F6-36-7B:
        media_content_id: '{ "playlist_name": "John Wick", "shuffle": "1" }'
        media_content_type: playlist
        announce_name: Playing a John Wick Movie
      17-9A-2C-7B:
        media_content_id: '{ "playlist_name": "Star Wars", "shuffle": "1" }'
        media_content_type: playlist
        announce_name: Playing A Star Wars Movie
      27-58-30-7B:
        media_content_id: '{ "playlist_name": "Tarantino", "shuffle": "1" }'
        media_content_type: playlist
        announce_name: Playing a Quentin Tarantino Movie
      77-EA-31-7B:
        media_content_id: '{ "playlist_name": "Agam", "shuffle": "1" }'
        media_content_type: playlist
      37-60-2D-7B:
        media_content_id: '{ "playlist_name": "Matrix", "shuffle": "1" }'
        media_content_type: playlist
        announce_name: Playing a Matrix Movie
      87-F4-2F-7B:
        media_content_id: '{ "library_name": "Movies", "title": "The Pursuit of Happyness"}'
        media_content_type: movie
        announce_name: Playing The Pursuit of Happyness
      F7-85-31-7B:
        media_content_id: '{ "library_name": "Movies", "title": "The Terminal"}'
        media_content_type: movie
        announce_name: Playing The Terminal
  max: 10
- id: music_spotify
  alias: "\U0001F3B5Music Jukebox"
  trigger:
  - platform: event
    event_type: tag_scanned
  condition:
  - condition: template
    value_template: '{{ trigger.event.data.tag_id in tags }}'
  action:
  - variables:
      uri: '{{ tags[trigger.event.data.tag_id].uri }}'
  - service: spotcast.start
    data:
      device_name: '{% if is_state(''media_player.spotify'', ''playing'') %} {{state_attr("media_player.spotify",
        "source")}} {%else%}{{ states(''input_select.speakers_spotify'') }}{%endif%}'
      uri: '{{ uri }}'
      random_song: true
      force_playback: true
      shuffle: true
  mode: restart
  variables:
    tags:
      04-BD-F1-F2-03-68-80:
        uri: spotify:playlist:2OTjSlEoXXnrv6L5ryw3sV?si=a00c6c678ef446c5
      04-C5-F1-F2-03-68-80:
        uri: spotify:playlist:5QTClPorWVvK650livXyEr?si=69a587c913554a73
      04-60-50-0A-22-6F-81:
        uri: spotify:playlist:37i9dQZF1DXaTIN6XNquoW?si=214e0d9999164539
      04-5C-51-0A-22-6F-81:
        uri: spotify:artist:4DHXXUP4qza7DacDKVT23G?si=k7eCA-BRRsaXNTzN0ulD5w
      04-6A-50-0A-22-6F-81:
        uri: spotify:playlist:7zozfVwEIRnlZVhWAjCvh4?si=ef9e4f4789d24d93
      04-73-50-0A-22-6F-81:
        uri: spotify:playlist:4McZ2miIU3GteSwmAAxCrJ?si=F0Vg19zkRTi3g3Y4DyQeMA
      04-77-51-0A-22-6F-81:
        uri: spotify:playlist:2DsO6uDqyONHtelhjUbYix?si=mFYPVbLaTnGI-IAQQiAYa
      04-53-51-0A-22-6F-81:
        uri: spotify:playlist:37i9dQZF1DZ06evO0KEAbC?si=be9f74962433475f
      04-4B-51-0A-22-6F-81:
        uri: spotify:playlist:10N88juIQN9zO7a2FdPpAr?si=puXar2w3QmS-byDzvCr5Mw
      04-3B-51-0A-22-6F-81:
        uri: spotify:playlist:42WlES4C0cTGvjO4aquO7f?si=IlBYKTckTnGxSz7chv6GpQ
      04-43-51-0A-22-6F-81:
        uri: spotify:playlist:113zomdc3VfahCRJ0vuVML?si=434e184ad0914c94
      04-10-51-0A-22-6F-81:
        uri: spotify:playlist:1DRN46YWHKyrZ6CmF1ykJw?si=pKimy_gJQJiBQeVzVXeoCA
      04-18-51-0A-22-6F-81:
        uri: spotify:playlist:7kWWQq0gZHaGmy4NfjnOj5?si=KDeC7IiATtSp3Qsro5njeg
      04-20-51-0A-22-6F-81:
        uri: spotify:playlist:37i9dQZF1DZ06evO1MVYmm?si=ZQxQ1t9zTzKq7lRgvfMP2Q
      04-33-51-0A-22-6F-81:
        uri: spotify:playlist:37i9dQZEVXcWjFlf2abaJx?si=c4588564cf784c02
      04-28-51-0A-22-6F-81:
        uri: spotify:artist:6XyY86QOPPrYVGvF9ch6wz?si=ANPiWS39QSGCWHBBMMW1Ow
      04-50-50-0A-22-6F-81:
        uri: spotify:album:4m2880jivSbbyEGAKfITCa?si=pacROChHSFSDEs5XIYtzTQ
      04-D5-F1-F2-03-68-80:
        uri: spotify:playlist:37i9dQZF1EJMBmrEbDk6wO?si=577fdf28736140e5
      04-CD-F1-F2-03-68-80:
        uri: spotify:playlist:37i9dQZF1EJBSlh2ABgMAk?si=7f1ec20760fc407d
      04-DD-F1-F2-03-68-80:
        uri: spotify:playlist:2XPCqkfm5o7HHjLZ4b4ntS?si=45d4f05eeaf04eff
- id: player_controls
  alias: "\U0001F3B5Player Controls"
  description: ''
  trigger:
  - platform: event
    event_type: tag_scanned
  condition:
  - condition: template
    value_template: '{{ trigger.event.data.tag_id in tags }}'
  action:
  - variables:
      service: '{{ tags[trigger.event.data.tag_id].service }}'
  - service: '{{ service }}'
    target:
      entity_id: media_player.spotify
  mode: restart
  variables:
    tags:
      previous:
        service: media_player.media_previous_track
      play/pause:
        service: media_player.media_play_pause
      next:
        service: media_player.media_next_track
- id: '1636123727125'
  alias: ⚙️Shopping list update
  description: ''
  trigger:
  - platform: state
    entity_id: input_text.shopping_list
  condition: []
  action:
  - service: script.add_shopping_list
    data: {}
  mode: single
- id: hacs_sensor_refresh
  alias: ⚙️HACS Sensor Refresh
  description: Refreshes the HACS sensor once an update is installed.
  trigger:
  - platform: event
    event_type: hacs/repository
    event_data:
      action: install
  action:
  - delay:
      seconds: 4
  - service: homeassistant.update_entity
    target:
      entity_id: sensor.hacs
  initial_state: true
- id: '1636974013216'
  alias: ⚙️Lovelace Reload
  description: ''
  trigger:
  - platform: event
    event_type: lovelace_updated
    event_data:
      url_path: lovelace-wallmount
    id: wallmount
  - platform: event
    event_type: lovelace_updated
    event_data:
      url_path:
    id: lovelace
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - choose:
    - conditions:
      - condition: trigger
        id: wallmount
      sequence:
      - service: browser_mod.refresh
        data: {}
        target:
          device_id: 534f77b165463f8e653c72beaa4d9399
    default: []
  mode: queued
- id: '1638974963835'
  alias: ⚙️Homeassistant Start/Stop
  description: Runs various automations based on homeassistant starting or stopping.
  trigger:
  - platform: homeassistant
    event: shutdown
    id: shutdown
  - platform: homeassistant
    event: start
    id: start
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: shutdown
      sequence: []
    - conditions:
      - condition: trigger
        id: start
      sequence:
      - service: pyscript.f1constructorstandings
        data: {}
      - service: pyscript.f1driverstandings
        data: {}
    default: []
  mode: single
- id: '1642654396519'
  alias: ⚙️Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.mobile_app_10pro
        data:
          message: '{{sensors}}'
          data:
            notification_icon: mdi:battery-alert
            color: red
      threshold: 15
- id: '1654855874344'
  alias: ⚙️Convert Lovelace configuration to yaml
  description: ''
  trigger:
  - platform: event
    event_type: lovelace_updated
    event_data: {}
  condition: []
  action:
  - service: shell_command.lovelace_default_convert
    data: {}
  - service: shell_command.lovelace_wallmount_convert
    data: {}
  mode: single
- id: '1655137751596'
  alias: ⚙️Tag Github with version when core updated
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition:
  - condition: template
    value_template: '{{states.sensor.current_version.state > states.sensor.n00bcodr_homeassistant_ireland_latest_tag.state}}'
  action:
  - service: notify.mobile_app_10pro
    data:
      message: Update tag in GitHub?
      title: Home Assistant Core Updated!
      data:
        notification_icon: mdi:git
        icon_url: https://github.com/home-assistant/assets/blob/master/logo/logo-small.png?raw=true
        color: red
        actions:
        - action: tag_update
          title: Update!
        - action: URI
          title: Open Repo
          uri: https://github.com/n00bcodr/homeassistant-ireland
  - wait_for_trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: tag_update
    continue_on_timeout: false
  - service: shell_command.git_core_update_push
    data: {}
  mode: single
- id: '1655814095516'
  alias: "\U0001F3AC\U0001F3F0Capture Shared URL - Google TV"
  description: Captures the URL shared and updates input_text ccgtv_share_url
  trigger:
  - platform: event
    event_type: mobile_app.share
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data|regex_search(''com.netflix'', ignorecase=TRUE)
          }}'
      sequence:
      - service: input_text.set_value
        data:
          value: '{{ trigger.event.data.text|regex_findall_index(find=''(http.*)'',
            ignorecase=TRUE) }}

            '
        target:
          entity_id: input_text.ccgtv_share_url
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data|regex_search(''com.amazon'', ignorecase=TRUE)
          }}'
      sequence:
      - service: input_text.set_value
        data:
          value: '{{ trigger.event.data.text|regex_findall_index(find=''(http.*)'',
            ignorecase=true)|replace ("&ref_=atv_dp_share_seas&r=web", "") }}

            '
        target:
          entity_id: input_text.ccgtv_share_url
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data|regex_search(''startv.hotstar'', ignorecase=TRUE)
          }}'
      sequence:
      - service: input_text.set_value
        data:
          value: '{{ trigger.event.data.text|regex_findall_index(find=''(http.*)'',
            ignorecase=TRUE) }}

            '
        target:
          entity_id: input_text.ccgtv_share_url
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data|regex_search(''youtu.be'', ignorecase=TRUE)
          }}'
      sequence:
      - service: input_text.set_value
        data:
          value: '{{ trigger.event.data.url|regex_findall_index(find=''(http.*)'',
            ignorecase=TRUE) }}

            '
        target:
          entity_id: input_text.ccgtv_share_url
    default:
    - service: notify.persistent_notification
      data:
        message: '{{ states(''input_text.ccgtv_share_url'') }}

          '
  - service: androidtv.adb_command
    data:
      entity_id: media_player.google_tv
      command: HOME
  - service: script.load_share_url_googletv
    data: {}
  mode: single
- id: '1659935815150'
  alias: ⚙️Update Formula1 Standings after every Race
  description: ''
  trigger:
  - platform: calendar
    event: end
    offset: 0:0:0
    entity_id: calendar.formula1_2022
  condition: []
  action:
  - service: pyscript.f1driverstandings
    data: {}
  - service: pyscript.f1constructorstandings
    data: {}
  mode: single
- id: '1670537821206'
  alias: Tag Desk is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 73a21e41-133b-484e-a5a7-e8a2a7df1085
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      device_id: d12db564ed70f93b24fe2e6cbca174b8
  mode: single
- id: '1670578939434'
  alias: "\U0001F3F0Button"
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 3fd72c6a517024c03b9531259c2d55d9
    type: action
    subtype: single
    discovery_id: 0x00124b001eaa8251 action_single
    id: click
  - platform: device
    domain: mqtt
    device_id: 3fd72c6a517024c03b9531259c2d55d9
    type: action
    subtype: double
    discovery_id: 0x00124b001eaa8251 action_double
    id: doubleclick
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: click
      sequence:
      - choose:
        - conditions:
          - condition: state
            entity_id: light.light
            state: 'on'
          sequence:
          - service: light.turn_off
            target:
              entity_id: light.light
            data: {}
        - conditions:
          - condition: state
            entity_id: light.light
            state: 'off'
          sequence:
          - service: light.turn_on
            target:
              entity_id: light.light
            data:
              color_temp: 500
              brightness: 255
        default: []
    - conditions:
      - condition: trigger
        id: doubleclick
      sequence:
      - choose:
        - conditions:
          - condition: state
            entity_id: light.light
            state: 'on'
          sequence:
          - service: light.turn_off
            target:
              entity_id: light.light
            data: {}
        - conditions:
          - condition: state
            entity_id: light.light
            state: 'off'
          sequence:
          - service: light.turn_on
            target:
              entity_id: light.light
            data:
              brightness: 255
              color_temp: 153
        default: []
    default: []
  mode: single
