- platform: template
  sensors:
    in_bed:
      friendly_name: In Bed?
      device_class: occupancy
      value_template: >-
        {{ not (is_state('binary_sensor.withings_in_bed_homeassistant', 'off') or is_state('binary_sensor.withings_in_bed_homeassistant', 'unavailable')) }}
      icon_template: "{{ iif(is_state('binary_sensor.in_bed', 'on'), 'mdi:bed', 'mdi:bed-outline') }}"

    den_motion:
      friendly_name: Den Motion
      device_class: motion
      value_template: >-
        {{ is_state('binary_sensor.den_motion_1_occupancy', 'on') or is_state('binary_sensor.den_motion_2_occupancy', 'on') }}

    chair_occupancy:
      friendly_name: "Chair Occupancy"
      device_class: occupancy
      value_template: "{{ is_state('binary_sensor.chair', 'off') or is_state('binary_sensor.vibration_vibration', 'on') }}"
      icon_template: "{{ iif(is_state('binary_sensor.chair_occupancy', 'on'), 'mdi:table-chair', 'mdi:account-off') }}"

    # True if there's an update available for supervisor
    updater_supervisor:
      friendly_name: "Updater Supervisor"
      device_class: problem
      value_template: "{{ state_attr('sensor.supervisor_updates', 'update_available') }}"
      availability_template: "{{ states('sensor.supervisor_updates') | int(-1) > -1 }}"

# True if there's updates available for any HACS components or Addons
- platform: threshold
  name: Updater HACS
  entity_id: sensor.hacs
  upper: 0.5

- platform: threshold
  name: Updater Addons
  entity_id: sensor.supervisor_updates
  upper: 0.5
