esphome:
  name: nfc-reader
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "21cfe7214e20c27e3942e4a75301b6f8"

wifi:
  ssid: "upadrasta"
  password: "Upadrasta"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nfc-Reader Fallback Hotspot"
    password: "XfR8jLrZSfSQ"

captive_portal:
