esphome:
  name: Tag Reader
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "upadrasta"
  password: "Upadrasta123"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tag Reader Fallback Hotspot"
    password: "jy5vD0Yy87MN"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
