esphome:
  name: tagreader

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "06318a47a0e376436443c910aca429e3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tagreader Fallback Hotspot"
    password: "wJRy0BLI8X5C"

captive_portal:
