# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cloud/alarm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/cloud/alarm.proto\x12\ralarm.message\"N\n\x05\x41larm\x12\r\n\x05hours\x18\x01 \x02(\r\x12\x0f\n\x07minutes\x18\x02 \x02(\r\x12\x12\n\nrepetition\x18\x03 \x02(\x08\x12\x11\n\tweek_info\x18\x04 \x02(\r\"v\n\x08SyncTime\x12\x0c\n\x04year\x18\x01 \x02(\r\x12\r\n\x05month\x18\x02 \x02(\r\x12\x0b\n\x03\x64\x61y\x18\x03 \x02(\r\x12\x0f\n\x07weekday\x18\x04 \x02(\r\x12\r\n\x05hours\x18\x05 \x02(\r\x12\x0f\n\x07minutes\x18\x06 \x02(\r\x12\x0f\n\x07seconds\x18\x07 \x02(\rB0\n#com.eufylife.smarthome.protobuftoolB\tAlarmInfo')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cloud.alarm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n#com.eufylife.smarthome.protobuftoolB\tAlarmInfo'
  _ALARM._serialized_start=42
  _ALARM._serialized_end=120
  _SYNCTIME._serialized_start=122
  _SYNCTIME._serialized_end=240
# @@protoc_insertion_point(module_scope)
