# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cloud/debug.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...proto.cloud import common_pb2 as proto_dot_cloud_dot_common__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/cloud/debug.proto\x12\x0bproto.cloud\x1a\x18proto/cloud/common.proto\"\x8b\x03\n\x0c\x44\x65\x62ugRequest\x12#\n\x06log_sw\x18\x01 \x01(\x0b\x32\x13.proto.cloud.Switch\x12;\n\x0c\x66\x61ult_report\x18\x02 \x01(\x0b\x32%.proto.cloud.DebugRequest.FaultReport\x12\'\n\ncapture_sw\x18\x03 \x01(\x0b\x32\x13.proto.cloud.Switch\x12?\n\x0eimage_feedback\x18\x04 \x01(\x0b\x32\'.proto.cloud.DebugRequest.ImageFeedback\x12-\n\x10toggle_mop_raise\x18\x0b \x01(\x0b\x32\x13.proto.cloud.Switch\x12,\n\x0ftoggle_mop_spin\x18\x0c \x01(\x0b\x32\x13.proto.cloud.Switch\x1a\x1a\n\x0b\x46\x61ultReport\x12\x0b\n\x03seq\x18\x01 \x01(\r\x1a\x36\n\rImageFeedback\x12\x13\n\x0bobject_type\x18\x01 \x01(\t\x12\x10\n\x08photo_id\x18\x02 \x01(\t\"\x9c\x02\n\rDebugResponse\x12#\n\x06log_sw\x18\x01 \x01(\x0b\x32\x13.proto.cloud.Switch\x12:\n\x0bupdate_info\x18\x02 \x01(\x0b\x32%.proto.cloud.DebugResponse.UpdateInfo\x12:\n\x0bwebtty_info\x18\x03 \x01(\x0b\x32%.proto.cloud.DebugResponse.WebTtyInfo\x12\'\n\ncapture_sw\x18\x04 \x01(\x0b\x32\x13.proto.cloud.Switch\x1a\x1e\n\nUpdateInfo\x12\x10\n\x08\x65rr_code\x18\x01 \x01(\r\x1a%\n\nWebTtyInfo\x12\x17\n\x0f\x63onnection_data\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cloud.debug_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEBUGREQUEST._serialized_start=67
  _DEBUGREQUEST._serialized_end=462
  _DEBUGREQUEST_FAULTREPORT._serialized_start=380
  _DEBUGREQUEST_FAULTREPORT._serialized_end=406
  _DEBUGREQUEST_IMAGEFEEDBACK._serialized_start=408
  _DEBUGREQUEST_IMAGEFEEDBACK._serialized_end=462
  _DEBUGRESPONSE._serialized_start=465
  _DEBUGRESPONSE._serialized_end=749
  _DEBUGRESPONSE_UPDATEINFO._serialized_start=680
  _DEBUGRESPONSE_UPDATEINFO._serialized_end=710
  _DEBUGRESPONSE_WEBTTYINFO._serialized_start=712
  _DEBUGRESPONSE_WEBTTYINFO._serialized_end=749
# @@protoc_insertion_point(module_scope)
