# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cloud/language.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/cloud/language.proto\x12\x0bproto.cloud\"\xb8\x02\n\x0fLanguageRequest\x12/\n\x04\x64\x65sc\x18\x01 \x01(\x0b\x32!.proto.cloud.LanguageRequest.Desc\x12\x39\n\tselection\x18\x02 \x01(\x0b\x32&.proto.cloud.LanguageRequest.Selection\x1aO\n\x04\x44\x65sc\x12\x0e\n\x06set_id\x18\x01 \x01(\r\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0b\n\x03md5\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\r\x12\x0c\n\x04size\x18\x05 \x01(\r\x1ah\n\tSelection\x12;\n\x05value\x18\x01 \x01(\x0e\x32,.proto.cloud.LanguageRequest.Selection.Value\"\x1e\n\x05Value\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x08\n\x04USER\x10\x01\"\xca\x01\n\x10LanguageResponse\x12\x12\n\ndefault_id\x18\x01 \x01(\r\x12\x12\n\ncurrent_id\x18\x02 \x01(\r\x12\x0f\n\x07version\x18\x03 \x01(\r\x12\x0e\n\x06set_id\x18\x04 \x01(\r\x12\x32\n\x05state\x18\x05 \x01(\x0e\x32#.proto.cloud.LanguageResponse.State\"9\n\x05State\x12\x08\n\x04IDLE\x10\x00\x12\x0c\n\x08UPDATING\x10\x01\x12\x0b\n\x07SUCCESS\x10\x02\x12\x0b\n\x07\x46\x41ILURE\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cloud.language_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LANGUAGEREQUEST._serialized_start=44
  _LANGUAGEREQUEST._serialized_end=356
  _LANGUAGEREQUEST_DESC._serialized_start=171
  _LANGUAGEREQUEST_DESC._serialized_end=250
  _LANGUAGEREQUEST_SELECTION._serialized_start=252
  _LANGUAGEREQUEST_SELECTION._serialized_end=356
  _LANGUAGEREQUEST_SELECTION_VALUE._serialized_start=326
  _LANGUAGEREQUEST_SELECTION_VALUE._serialized_end=356
  _LANGUAGERESPONSE._serialized_start=359
  _LANGUAGERESPONSE._serialized_end=561
  _LANGUAGERESPONSE_STATE._serialized_start=504
  _LANGUAGERESPONSE_STATE._serialized_end=561
# @@protoc_insertion_point(module_scope)
