# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cloud/map_manage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...proto.cloud import common_pb2 as proto_dot_cloud_dot_common__pb2
from ...proto.cloud import stream_pb2 as proto_dot_cloud_dot_stream__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/cloud/map_manage.proto\x12\x0bproto.cloud\x1a\x18proto/cloud/common.proto\x1a\x18proto/cloud/stream.proto\"\xd7\x01\n\tMapEntity\x12)\n\x04\x64\x65sc\x18\x01 \x01(\x0b\x32\x1b.proto.cloud.MapEntity.Desc\x12\r\n\x05pixel\x18\x02 \x01(\x0c\x1a\x8f\x01\n\x04\x44\x65sc\x12\x0e\n\x06map_id\x18\x01 \x01(\r\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x12\n\nresolution\x18\x04 \x01(\r\x12\"\n\x06origin\x18\x05 \x01(\x0b\x32\x12.proto.cloud.Point\x12 \n\x05\x64ocks\x18\x06 \x03(\x0b\x32\x11.proto.cloud.Pose\"\xc2\x01\n\tMapExtras\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x35\n\x0croom_outline\x18\x02 \x03(\x0b\x32\x1f.proto.cloud.stream.RoomOutline\x12\x33\n\x0broom_params\x18\x03 \x03(\x0b\x32\x1e.proto.cloud.stream.RoomParams\x12;\n\x0frestricted_zone\x18\x04 \x01(\x0b\x32\".proto.cloud.stream.RestrictedZoneb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cloud.map_manage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPENTITY._serialized_start=98
  _MAPENTITY._serialized_end=313
  _MAPENTITY_DESC._serialized_start=170
  _MAPENTITY_DESC._serialized_end=313
  _MAPEXTRAS._serialized_start=316
  _MAPEXTRAS._serialized_end=510
# @@protoc_insertion_point(module_scope)
