# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cloud/misc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...proto.cloud import common_pb2 as proto_dot_cloud_dot_common__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/cloud/misc.proto\x12\x0bproto.cloud\x1a\x18proto/cloud/common.proto\"\x17\n\x06Volume\x12\r\n\x05value\x18\x01 \x01(\r\"(\n\x05Power\x12\x1f\n\x02sw\x18\x01 \x01(\x0b\x32\x13.proto.cloud.Switch\"\x18\n\x07\x42\x61ttery\x12\r\n\x05level\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cloud.misc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOLUME._serialized_start=65
  _VOLUME._serialized_end=88
  _POWER._serialized_start=90
  _POWER._serialized_end=130
  _BATTERY._serialized_start=132
  _BATTERY._serialized_end=156
# @@protoc_insertion_point(module_scope)
