# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cloud/multi_maps.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...proto.cloud import common_pb2 as proto_dot_cloud_dot_common__pb2
from ...proto.cloud import p2pdata_pb2 as proto_dot_cloud_dot_p2pdata__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/cloud/multi_maps.proto\x12\x0bproto.cloud\x1a\x18proto/cloud/common.proto\x1a\x19proto/cloud/p2pdata.proto\"\xe4\x04\n\x16MultiMapsManageRequest\x12:\n\x06method\x18\x01 \x01(\x0e\x32*.proto.cloud.MultiMapsManageRequest.Method\x12\x0b\n\x03seq\x18\x02 \x01(\r\x12<\n\x06rename\x18\x03 \x01(\x0b\x32*.proto.cloud.MultiMapsManageRequest.RenameH\x00\x12<\n\x06\x63ommon\x18\x04 \x01(\x0b\x32*.proto.cloud.MultiMapsManageRequest.CommonH\x00\x12G\n\x0csave_options\x18\x05 \x01(\x0b\x32/.proto.cloud.MultiMapsManageRequest.SaveOptionsH\x00\x1a/\n\x06Rename\x12\x13\n\x0b\x63loud_mapid\x18\x01 \x01(\r\x12\x10\n\x08new_name\x18\x02 \x01(\t\x1a\x1d\n\x06\x43ommon\x12\x13\n\x0b\x63loud_mapid\x18\x01 \x01(\r\x1a\x38\n\x0bSaveOptions\x12)\n\x0cmulti_map_sw\x18\x01 \x01(\x0b\x32\x13.proto.cloud.Switch\"\xa8\x01\n\x06Method\x12\r\n\tMAP_RESET\x10\x00\x12\x0e\n\nMAP_RENAME\x10\x01\x12\x0c\n\x08MAP_LOAD\x10\x02\x12\x0f\n\x0bMAP_REPLACE\x10\x03\x12\x0e\n\nMAP_DELETE\x10\x04\x12\x0c\n\x08MAP_SAVE\x10\x05\x12\x0e\n\nMAP_IGNORE\x10\x06\x12\x0f\n\x0bMAP_GET_ALL\x10\x07\x12\x0f\n\x0bMAP_GET_ONE\x10\x08\x12\x10\n\x0cMAP_RECOVERY\x10\tB\x07\n\x05Param\"\x97\x03\n\x17MultiMapsManageResponse\x12:\n\x06method\x18\x01 \x01(\x0e\x32*.proto.cloud.MultiMapsManageRequest.Method\x12\x0b\n\x03seq\x18\x02 \x01(\r\x12;\n\x06result\x18\x03 \x01(\x0e\x32+.proto.cloud.MultiMapsManageResponse.Result\x12-\n\tmap_infos\x18\x0b \x01(\x0b\x32\x18.proto.cloud.p2p.MapInfoH\x00\x12J\n\rcomplete_maps\x18\x0c \x01(\x0b\x32\x31.proto.cloud.MultiMapsManageResponse.CompleteMapsH\x00\x1a\x42\n\x0c\x43ompleteMaps\x12\x32\n\x0c\x63omplete_map\x18\x01 \x03(\x0b\x32\x1c.proto.cloud.p2p.CompleteMap\".\n\x06Result\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x0b\n\x07STARTED\x10\x02\x42\x07\n\x05Paramb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cloud.multi_maps_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MULTIMAPSMANAGEREQUEST._serialized_start=99
  _MULTIMAPSMANAGEREQUEST._serialized_end=711
  _MULTIMAPSMANAGEREQUEST_RENAME._serialized_start=395
  _MULTIMAPSMANAGEREQUEST_RENAME._serialized_end=442
  _MULTIMAPSMANAGEREQUEST_COMMON._serialized_start=444
  _MULTIMAPSMANAGEREQUEST_COMMON._serialized_end=473
  _MULTIMAPSMANAGEREQUEST_SAVEOPTIONS._serialized_start=475
  _MULTIMAPSMANAGEREQUEST_SAVEOPTIONS._serialized_end=531
  _MULTIMAPSMANAGEREQUEST_METHOD._serialized_start=534
  _MULTIMAPSMANAGEREQUEST_METHOD._serialized_end=702
  _MULTIMAPSMANAGERESPONSE._serialized_start=714
  _MULTIMAPSMANAGERESPONSE._serialized_end=1121
  _MULTIMAPSMANAGERESPONSE_COMPLETEMAPS._serialized_start=998
  _MULTIMAPSMANAGERESPONSE_COMPLETEMAPS._serialized_end=1064
  _MULTIMAPSMANAGERESPONSE_RESULT._serialized_start=1066
  _MULTIMAPSMANAGERESPONSE_RESULT._serialized_end=1112
# @@protoc_insertion_point(module_scope)
