# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cloud/socket.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...proto.cloud import ble_pb2 as proto_dot_cloud_dot_ble__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/cloud/socket.proto\x12\x0bproto.cloud\x1a\x15proto/cloud/ble.proto\"F\n\x0fSocketBroadcast\x12\x0f\n\x07is_bind\x18\x01 \x01(\x08\x12\x11\n\tdevice_sn\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"B\n\x0cSocketVerify\x12\x0e\n\x06random\x18\x01 \x01(\t\x12\x11\n\tdevice_sn\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"\x9c\x01\n\x0fSocketTransData\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.proto.cloud.SocketTransData.Type\x12\x34\n\ndistribute\x18\x02 \x01(\x0b\x32 .proto.cloud.BtAppMsg.Distribute\"\"\n\x04Type\x12\x10\n\x0c\x45_DISTRIBUTE\x10\x00\x12\x08\n\x04\x45_DP\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cloud.socket_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOCKETBROADCAST._serialized_start=64
  _SOCKETBROADCAST._serialized_end=134
  _SOCKETVERIFY._serialized_start=136
  _SOCKETVERIFY._serialized_end=202
  _SOCKETTRANSDATA._serialized_start=205
  _SOCKETTRANSDATA._serialized_end=361
  _SOCKETTRANSDATA_TYPE._serialized_start=327
  _SOCKETTRANSDATA_TYPE._serialized_end=361
# @@protoc_insertion_point(module_scope)
