# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cloud/upgrade.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/cloud/upgrade.proto\x12\x0bproto.cloud\"\x14\n\x12QueryUpgradeStatus\"\x95\x03\n\rUpgradeStatus\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.proto.cloud.UpgradeStatus.Status\x12\x10\n\x08progress\x18\x02 \x01(\r\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x89\x01\n\x06Status\x12\x08\n\x04IDLE\x10\x00\x12\x0f\n\x0b\x44OWNLOADING\x10\x01\x12\x15\n\x11\x44OWNLOAD_COMPLETE\x10\x02\x12\x13\n\x0f\x44OWNLOAD_FAILED\x10\x03\x12\x0e\n\nINSTALLING\x10\x04\x12\x14\n\x10INSTALL_COMPLETE\x10\x05\x12\x12\n\x0eINSTALL_FAILED\x10\x06\"\xa3\x01\n\x05\x45rror\x12\x08\n\x04NONE\x10\x00\x12\x12\n\x0eNOT_IN_STATION\x10\x01\x12\x16\n\x12\x42\x41TTERY_NOT_ENOUGH\x10\x02\x12\x16\n\x12MCU_INSTALL_FAILED\x10\x03\x12\x15\n\x11\x41P_INSTALL_FAILED\x10\x04\x12\x19\n\x15STATION_NOT_CONNECTED\x10\x05\x12\x1a\n\x16STATION_INSTALL_FAILED\x10\x06\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cloud.upgrade_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERYUPGRADESTATUS._serialized_start=42
  _QUERYUPGRADESTATUS._serialized_end=62
  _UPGRADESTATUS._serialized_start=65
  _UPGRADESTATUS._serialized_end=470
  _UPGRADESTATUS_STATUS._serialized_start=167
  _UPGRADESTATUS_STATUS._serialized_end=304
  _UPGRADESTATUS_ERROR._serialized_start=307
  _UPGRADESTATUS_ERROR._serialized_end=470
# @@protoc_insertion_point(module_scope)
