reload:
  name: "Reload"
  description: Reload localtuya and reconnect to all devices.

set_dp:
  name: "Set DP Value"
  description: Change the value of a datapoint (DP)
  fields:
    device_id:
      name: "Device ID"
      description: Device ID of device to change datapoint value for
      required: true
      example: 11100118278aab4de001
      selector:
        text:
    dp:
      name: "DP"
      description: Target DP, Datapoint index
      required: false
      example: 1
      selector:
        number:
          mode: box
    value:
      name: "Value"
      description: "New value to set or list of dp: value, If value is list target dp will be ignored"
      required: true
      example: '{ "1": True, "2": True }'
      selector:
        object:
