esphome:
  name: bluetoothproxy

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Bluetoothproxy Fallback Hotspot"
    password: "123456789"

captive_portal:

bluetooth_proxy:
esp32_ble_tracker: