add_radarr_movie:
  description: "Add a movie to Radarr"
  fields:
    title:
      description: "Title of the movie"
      example: "Gladiator"

add_sonarr_tv_show:
  description: "Add a TV show to Sonarr"
  fields:
    title:
      description: "Title of the TV show"
      example: "Breaking Bad"

add_overseerr_movie:
  description: "Add a movie to Overseerr"
  fields:
    title:
      description: "Title of the movie"
      example: "Gladiator"

add_overseerr_tv_show:
  description: "Add a TV show to Overseerr"
  fields:
    title:
      description: "Title of the TV show"
      example: "Breaking Bad"